### ISSUE TITLE
Remove unused import

### ISSUE THREAD

**Issue by cardil** [wavesoftware/sampler#2]
https://github.com/wavesoftware/sampler/blob/337fbacdc8034bc23e46a5f8c5839e7e242ff4fd/sampler-api/src/main/java/pl/wavesoftware/sampler/api/RandomSource.java#L20

**Comment by Vignesh-Durairaj** [comment]
I will take this up ! It'll help me understand the open-source-contribution life cycle.

**Comment by Vignesh-Durairaj** [comment]
Pull request #4 has been raised, which may fix/close this issue. Kindly review the same.
